spring.application.name=tienda-yuliana

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda
spring.datasource.username=postgres
spring.datasource.password=854400gf
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=tienda_yuliana
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Jackson timezone
spring.jackson.time-zone=UTC

# Server
server.port=8081
